replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5678

resources:
  limits:
    cpu: 60m
    memory: 32Mi
  requests:
    cpu: 5m
    memory: 16Mi

args:
  - "-text=API Backend Service"
