apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
