apiVersion: v2
name: prometheus
description: Prometheus monitoring stack for dev cluster
type: application
version: 1.0.0
appVersion: "2.50.0"
dependencies:
  - name: kube-prometheus-stack
    version: 56.6.2
    repository: https://prometheus-community.github.io/helm-charts
