apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tmc
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: data-validator
  cluster: cluster-eu-west-1
  tmc: "true"
