apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tmc
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: pipeline-orchestrator
  cluster: cluster-us-east-1
  tmc: "true"
