apiVersion: v1
kind: Service
metadata:
  name: tracing-service
spec:
  selector:
    app: tracing-service
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
