apiVersion: v1
kind: Service
metadata:
  name: experiment-tracker
spec:
  selector:
    app: experiment-tracker
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
