apiVersion: v1
kind: Service
metadata:
  name: image-recognition
spec:
  selector:
    app: image-recognition
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
