apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tmc
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: text-to-speech
  cluster: cluster-us-west-2
  tmc: "true"
