apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection
spec:
  selector:
    app: anomaly-detection
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
