apiVersion: v1
kind: Service
metadata:
  name: time-series-forecast
spec:
  selector:
    app: time-series-forecast
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
