apiVersion: v1
kind: Service
metadata:
  name: recommendation-engine
spec:
  selector:
    app: recommendation-engine
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
