apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: metrics-collector
  releaseName: metrics-collector
  namespace: dev
  valuesFile: values.yaml
  includeCRDs: false
